version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./code:/code
      - ./services/web/config/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes: 
      - ./code:/code
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  mysql:
    image: mysql:5.6.39
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
